### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by Hades32** [chenht2010/Voicebox#2]
Hey @chenht2010 , found this when checking out https://github.com/lucidrains/voicebox-pytorch

Would you mind sharing pre-trained model weights? I'd like to try this out, but don't want to spend days training a full model...

**Comment by chenht2010** [comment]
OK, I'll upload weights soon.

**Comment by chenht2010** [comment]
Done. Weights uploaded.

**Comment by Hades32** [comment]
Cool, thanks!
