### ISSUE TITLE
How to support Zero-shot text-to-speech synthesis?

### ISSUE THREAD

**Issue by blldd** [chenht2010/Voicebox#3]
Hi Haitao, I have a question about model usage. Based on LJdataset and demos, I found that the model supports **content editing** and may not support **zero-shot text-to-speech synthesis** (I guess, since LJdataset has only one character and is tested on this role), so if I want to adapt the imitation ability to more characters with just a 10-second prompt, what can I do to achieve this?

**Comment by chenht2010** [comment]
As the paper says, you can just put the new phone sequence behind or before a reference sentence.

We don't have dur model, I will use textgrid as example. For example, you have two textgrid, one has wav,the other is the one you want synthsis, you can combine two textgrid, use the phone sequence as input, mel condition is the mel followed by all zeros,the whole length is the length of two textgrid.


I think your question is how to get the text's phone sequence. This is done by dur model.

**Comment by blldd** [comment]
Thanks for the explanation, actually I'm trying to figure out how to implement the ability validated in the paper and demo, such as zero-shot text-to-speech synthesis, because I think the model should be trained on more characters to be able to learn more features of timbre tones, so as to achieve zero-shot text-to-speech synthesis, and the paper mentions that MLJ uses 70K hours of multi-role data, so I'm guessing that zero-shot text-to-speech synthesis cannot be supported just using simple single-role data like ljspeech?

**Comment by chenht2010** [comment]
Yes, need multiple speaker dataset

**Comment by blldd** [comment]
Will you train on the MLJ dataset next?

**Comment by chenht2010** [comment]
No resource to do this.
